CREATE TABLE oauth_clients (
    id BIGINT,
    name VARCHAR(127) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_oauth_clients PRIMARY KEY(id),
    CONSTRAINT uq_oauth_clients_name UNIQUE (name)
) DEFAULT CHARACTER SET = utf8mb4,
ENGINE = InnoDB;
